include: package:pedantic/analysis_options.yaml

analyzer:
  errors:
    undefined_prefixed_name: ignore
    omit_local_variable_types: ignore
    unsafe_html: ignore
linter:
  rules:
    - always_put_required_named_parameters_first
    - avoid_print
    - avoid_redundant_argument_values
    - prefer_const_constructors
