name: Report a bug
description: Report issues with Flutter Quill, including crashes, exceptions, buggy widgets, or unexpected behavior.
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following details to help us address your issue effectively.

  - type: checkboxes
    attributes:
      label: Have you checked for an existing issue?
      description: Ensure there isn’t already an open issue for this feature request.
      options:
      - label: I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
        required: true
  - type: input
    attributes:
      label: Flutter Quill Version
      description: The relevant package versions
      placeholder: e.g., 10.0.0
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide a clear step-by-step guide to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected results
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual results
      description: Describe what is happening instead of the expected behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any extra information such as screenshots, videos, or logs to help diagnose the issue.

        Consider sharing the `pubspec.lock` file of the project if relevant.

        If the logs are too large to be uploaded to GitHub, you may upload
        them as a `txt` file or use online tools like https://pastebin.com to
        share it.
      value: |
        <details>
        <summary>Screenshots / Video demonstration</summary>

        [Attach media here]

        </details>

        <details><summary>Logs</summary>

        ```console
        [Paste logs here]
        ```

        </details>
    validations:
      required: false