name: Feature request
description: Propose a new idea or enhancement for Flutter Quill.
labels: 'enhancement'
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following details to help us evaluate your feature request.

  - type: checkboxes
    attributes:
      label: Have you checked for an existing issue?
      description: Ensure there isn’t already an open issue for this feature request.
      options:
        - label: I have searched the [existing issues](https://github.com/singerdmx/flutter-quill/issues)
          required: true
  - type: textarea
    attributes:
      label: Use case
      description: |
        Describe the problem or challenge that led to this feature request. 
        Include any alternative solutions you’ve considered and why they don’t work.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Describe your proposed solution and what you’d like Flutter Quill to do.

        You can include additional resources such as:
         - Images
         - Videos
         - Code samples
    validations:
      required: true