// Mocks generated by Mockito 5.0.17 from annotations
// in flutter_keyboard_visibility/test/flutter_keyboard_visibility_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_keyboard_visibility/src/keyboard_visibility_controller.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [KeyboardVisibilityController].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyboardVisibilityController extends _i1.Mock
    implements _i2.KeyboardVisibilityController {
  MockKeyboardVisibilityController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<bool> get onChange =>
      (super.noSuchMethod(Invocation.getter(#onChange),
          returnValue: Stream<bool>.empty()) as _i3.Stream<bool>);
  @override
  bool get isVisible =>
      (super.noSuchMethod(Invocation.getter(#isVisible), returnValue: false)
          as bool);
}
