codecov:
  require_ci_to_pass: yes

coverage:
  range: 55..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        branches:
          - master
    patch: off

comment:
  layout: 'reach, diff, files'