enum ToolbarButtons {
  // Not needed anymore, the dev can customize this much easier now
  // in the toolbarConfigurations of the QuillProvider
  undo,
  redo,
  fontFamily,
  fontSize,
  bold,
  subscript,
  superscript,
  italic,
  small,
  underline,
  strikeThrough,
  inlineCode,
  color,
  backgroundColor,
  clearFormat,
  centerAlignment,
  leftAlignment,
  rightAlignment,
  justifyAlignment,
  direction,
  headerStyle,
  listNumbers,
  listBullets,
  listChecks,
  codeBlock,
  quote,
  indentIncrease,
  indentDecrease,
  link,
  search,
}
