name: Code Quality Checks

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Verify Flutter installation
        run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get
      
      - name: Install flutter_quill_extensions dependencies
        run: flutter pub get -C flutter_quill_extensions

      - name: Install flutter_quill_test dependencies
        run: flutter pub get -C flutter_quill_test

      - name: Perform Flutter Analysis
        run: flutter analyze

      - name: Check Dart code formatting
        run: dart format --set-exit-if-changed .
      
      - name: Preview Dart proposed changes
        run: dart fix --dry-run

      - name: Check if the flutter_quill package is ready for publishing
        run: flutter pub publish --dry-run

      - name: Check if the flutter_quill_extensions is ready for publishing
        run: flutter pub publish --dry-run -C flutter_quill_extensions

      - name: Check the translations
        run: dart ./scripts/translations_check.dart

      - name: Install cider
        run: dart pub global activate cider

      # TODO: Need a more strict way to validate the format that uses https://keepachangelog.com/en/1.1.0/
      - name: Validate CHANGELOG.md format
        run: $HOME/.pub-cache/bin/cider list CHANGELOG.md
